FROM node:12-slim as build

# stable layers
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
RUN yarn add react-scripts@4.0.1 -g --silent

# dependencies that may change
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile

# source code
COPY . ./
RUN yarn run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]